// Regenerates src/generated/ from Relay's public OpenAPI spec.
// Source: RELAY_SPEC_URL, else `${RELAY_BASE_URL}/v2/openapi-public.json` (staging in CI), else prod.
import { readFile, writeFile } from "node:fs/promises";
import openapiTS, { astToString } from "openapi-typescript";

const base = process.env.RELAY_BASE_URL || "https://relaygpu.com";
const specUrl = process.env.RELAY_SPEC_URL || `${base.replace(/\/$/, "")}/v2/openapi-public.json`;

const res = await fetch(specUrl);
if (!res.ok) throw new Error(`spec fetch failed: ${res.status} ${specUrl}`);
const spec = await res.json();

const banner = "// GENERATED by scripts/gen.mjs from the public OpenAPI spec. Do not edit; run `npm run gen`.\n";

const ast = await openapiTS(spec, { alphabetize: true, exportType: true });
let types = astToString(ast);
// openapi-typescript marks deprecated ops on `paths` only; mirror it on `operations` too.
const deprecated = Object.values(spec.paths).flatMap((item) => Object.values(item)).filter((op) => op?.deprecated).map((op) => op.operationId);
for (const id of deprecated) types = types.replace(new RegExp(`^(    )${id}: \\{$`, "m"), `$1/** @deprecated No live model serves this operation. */\n$1${id}: {`);
await writeFile(new URL("../src/generated/openapi.ts", import.meta.url), banner + "/* eslint-disable */\n" + types);

// Error-code subclasses: codes from x-relay-error-codes, HTTP status from the hand-kept map.
const codes = spec.components.schemas.RelayError.properties.code["x-relay-error-codes"];
const statuses = JSON.parse(await readFile(new URL("../src/error-statuses.json", import.meta.url), "utf8"));
const BASES = { 400: "InvalidRequestError", 401: "AuthenticationError", 402: "InsufficientCreditsError", 403: "PermissionDeniedError", 404: "NotFoundError", 409: "ConflictError", 410: "GoneError", 422: "ValidationError", 429: "RateLimitError", 500: "RelayInternalError", 502: "ProviderError", 503: "CapacityError", 504: "UpstreamTimeoutError" };
const pascal = (code) => code.toLowerCase().replace(/(^|_)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
const className = (code) => (code.endsWith("_ERROR") ? pascal(code) : pascal(code) + "Error");

const unmapped = codes.filter((c) => !(c in statuses));
if (unmapped.length) console.warn(`gen: no HTTP status in src/error-statuses.json for ${unmapped.join(", ")} — they degrade to their response status class`);

const lines = [banner, `import { ${[...new Set(Object.values(BASES))].sort().join(", ")}, RelayAPIError } from "../errors-base.js";`, ""];
const table = [];
for (const code of codes) {
  const status = statuses[code];
  const base = BASES[status] ?? "RelayAPIError";
  const name = className(code);
  if (name === base) { table.push(`  ${code}: ${base},`); continue; } // the code IS the base (e.g. VALIDATION_ERROR)
  lines.push(`/** \`${code}\`${status ? ` (HTTP ${status})` : ""}. */`, `export class ${name} extends ${base} {}`);
  table.push(`  ${code}: ${name},`);
}
lines.push("", "/** Every catalog code (`x-relay-error-codes`) → its class. */", "export const ERROR_CODE_CLASSES = {", ...table, "} as const;", "", `export type RelayErrorCode = keyof typeof ERROR_CODE_CLASSES;`, "");
await writeFile(new URL("../src/generated/errors.ts", import.meta.url), lines.join("\n"));
console.log(`gen: ${specUrl} → src/generated/ (${Object.keys(spec.paths).length} paths, ${codes.length} error codes)`);
